# Title shown in Application Information tab.
title: VCN Creation Form
# Sub Title shown in Application Information tab.
description: This is used to create VCN , based on natura Template
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: https://www.naturaeco.com/wp-content/themes/mziq_naturaeco_inst/img/naturaandco.svg


locale: "en"
groupings:
  - title: "Cloud Configuration"
    variables:
    - region
    - compartment_id

  - title: "VCN Settings"
    - vcn_cidr
    - vcn_name

  - title: "Subnets"
    - create_public_subnet
    - public_subnet_cidr
    - public_subnet_name
    - create_private_app
    - private_app_subnet_cidr
    - private_app_subnet_name
    - create_private_db
    - private_db_subnet_cidr
    - private_db_subnet_name
    - create_private_exacs
    - private_exacs_server_subnet_cidr
    - private_exacs_server_subnet_name
    - private_exacs_bkp_subnet_cidr
    - private_exacs_bkp_subnet_name
    - create_private_oke
    - private_oke_subnet_cidr
    - private_oke_subnet_name
    - create_private_gen1
    - private_gen1_subnet_cidr
    - private_gen1_subnet_name
    - create_private_gen2
    - private_gen2_subnet_cidr
    - private_gen2_subnet_name
    - vcn_dns_label
    - lockdown_default_seclist

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created
    required: true

  compartment_id:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to create all resources
    required: true

  label_prefix:
    type: string
    title: Label Prefix
    description: a string that will be prepended to all resources
    required: false
    default: dev

  vcn_cidrs:
    type: list(string)
    title: VCN CIDR
    default: ["10.0.0.0/16"]
    required: true

  vcn_name:
    type: string
    title: VCN Name
    required: true
    default: TestVCN

  create_public_subnet:
    type: boolean
    title: "Create Public SubNet"
    description: "Check it if is necessary create public subnet"
    required: true
    default: false

  public_subnet_cidr:
    type: string
    title: Public SubNet CIDR
    required: false
    default: false
    visible: create_public_subnet
  
  public_subnet_name:
    type: string
    title: Public SubNet Name
    required: false
    default: false
    visible: create_public_subnet

  create_private_app:
    type: boolean
    title: "Create Private App SubNet"
    description: "Check it if is necessary create private app subnet"
    required: true
    default: false

  private_app_subnet_cidr:
    type: string
    title: Private App SubNet CIDR
    required: false
    default: false
    visible: create_private_app
  
  private_app_subnet_name:
    type: string
    title: Private App SubNet Name
    required: false
    default: false
    visible: create_private_app
  
  private_db_subnet_cidr:
    type: string
    title: Private DB SubNet CIDR
    required: false
    default: "10.0.3.0/24"
    visible: 
  
  private_db_subnet_name:
    type: string
    title: Private DB SubNet Name
    required: false
    default: "TestDBSN"
    visible: 
  
  private_exacs_server_subnet_cidr:
    type: string
    title: Private ExaCS Server SubNet CIDR
    required: false
    default: "10.0.4.0/24"
    visible: 
  
  private_exacs_server_subnet_name:
    type: string
    title: Private ExaCS Client SubNet Name
    required: false
    default: "TestExaCSCliSN"
    visible: 
  
  private_exacs_bkp_subnet_cidr:
    type: string
    title: Private ExaCS Backup SubNet CIDR
    required: false
    default: "10.0.5.0/24"
    visible: 
  
  private_exacs_bkp_subnet_name:
    type: string
    title: Private ExaCS Backup SubNet Name
    required: false
    default: "TestExaBkpCliSN"
    visible: 
  
  private_oke_subnet_cidr:
    type: string
    title: Private OKE SubNet CIDR
    required: false
    default: "10.0.6.0/24"
    visible: 
  
  private_oke_subnet_name:
    type: string
    title: Private OKE SubNet Name
    required: false
    default: "TestOKESN"
    visible: 
  
  private_gen1_subnet_cidr:
    type: string
    title: Private Generic SubNet Name 1
    required: false
    default: "10.0.7.0/24"
    visible: 
  
  private_gen1_subnet_name:
    type: string
    title: Private Generic SubNet Name 1
    required: false
    default: "TestGen1SN"
    visible: 
  
  private_gen2_subnet_cidr:
    type: string
    title: Private Generic SubNet CIDR 2
    required: false
    default: "10.0.8.0/24"
    visible: 
  
  private_gen2_subnet_name:
    type: string
    title: Private Generic SubNet Name 2
    required: false
    default: "TestGen2SN"
    visible: 
  
  vcn_dns_label:
    title: VCN DNS Label
    type: string
    required: false
    default: templatevcn

  lockdown_default_seclist:
    title: Enable VCN Default Security List Lockdown
    type: string
    required: false
    default: true

  attached_drg_id:
    title: DRG OCID to attach to the VCN
    type: string
    required: false
    default: null

  freeform_tags:
    type: map
    visible: false
