# Title shown in Application Information tab.
title: VCN Creation Form
# Sub Title shown in Application Information tab.
description: This is used to create VCN , based on natura Template
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: https://www.naturaeco.com/wp-content/themes/mziq_naturaeco_inst/img/naturaandco.svg


locale: "en"
groupings:
  - title: "Cloud Configuration"
    variables:
    - region
    - compartment_id

  - title: "VCN Settings"
    variables:
    - vcn_cidrs
    - vcn_name
    - vcn_dns_label
    - create_label_prefix
    - label_prefix
    - lockdown_default_seclist
    - create_internet_gateway
    - internet_gateway_display_name
    - create_nat_gateway
    - nat_gateway_display_name
    - create_service_gateway
    - service_gateway_display_name
    - enable_ipv6

  - title: "Subnets"
    variables:
    - create_public_subnet
    - public_subnet_cidr
    - public_subnet_name
    - create_private_app
    - private_app_subnet_cidr
    - private_app_subnet_name
    - create_private_db
    - private_db_subnet_cidr
    - private_db_subnet_name
    - create_private_exacs
    - private_exacs_client_subnet_cidr
    - private_exacs_client_subnet_name
    - private_exacs_bkp_subnet_cidr
    - private_exacs_bkp_subnet_name
    - create_private_oke
    - private_oke_subnet_cidr
    - private_oke_subnet_name
    - create_private_gen1
    - private_gen1_subnet_cidr
    - private_gen1_subnet_name
    - create_private_gen2
    - private_gen2_subnet_cidr
    - private_gen2_subnet_name

variables:
  region:
    type: oci:identity:region:name
    title: Region
    description: The OCI region where resources will be created
    required: true

  compartment_id:
    type: oci:identity:compartment:id
    title: Target Compartment
    description: The target compartment id where to create all resources
    required: true

  create_label_prefix:
    type: boolean
    title: "Create Label Prefix"
    description: "Check it if is necessary create label prefix"
    required: true

  label_prefix:
    type: string
    title: Label Prefix
    description: a string that will be prepended to all resources
    required: false
    default: null
    visible: create_label_prefix

  vcn_cidrs:
    type: list(string)
    title: VCN CIDR
    default: ["10.0.0.0/16"]
    required: true

  vcn_name:
    type: string
    title: VCN Name
    required: true
    default: TestVCN

  create_internet_gateway:
    type: boolean
    title: "Create Internet Gateway"
    description: "Check it if is necessary create label prefix"
    required: true

  internet_gateway_display_name:
    type: string
    title: Internet Gateway Display Name
    default: internet-gateway
    required: false
    visible: create_internet_gateway

  create_nat_gateway:
    type: boolean
    title: "Create NAT Gateway"
    description: "Check it if is necessary create label prefix"
    required: true

  nat_gateway_display_name:
    type: string
    title: NAT Gateway Display Name
    default: nat-gateway
    required: false
    visible: create_nat_gateway

  create_service_gateway:
    type: boolean
    title: "Create Service Gateway"
    description: "Check it if is necessary create label prefix"
    required: true

  service_gateway_display_name:
    type: string
    title: NAT Gateway Display Name
    required: false
    default: service-gateway
    visible: create_service_gateway

  enable_ipv6:
    type: boolean
    title: "Enable IPV6"
    description: "Check it if is necessary enable Ipv6"
    required: true

  create_public_subnet:
    type: boolean
    title: "Create Public SubNet"
    description: "Check it if is necessary create public subnet"
    required: true

  public_subnet_cidr:
    type: string
    title: Public SubNet CIDR
    required: false
    visible: create_public_subnet
  
  public_subnet_name:
    type: string
    title: Public SubNet Name
    required: false
    visible: create_public_subnet

  create_private_app:
    type: boolean
    title: "Create Private App SubNet"
    description: "Check it if is necessary create private app subnet"
    required: true

  private_app_subnet_cidr:
    type: string
    title: Private App SubNet CIDR
    required: false
    visible: create_private_app
  
  private_app_subnet_name:
    type: string
    title: Private App SubNet Name
    required: false
    visible: create_private_app

  create_private_db:
    type: boolean
    title: "Create Private DB SubNet"
    description: "Check it if is necessary create private database subnet"
    required: true
    
  private_db_subnet_cidr:
    type: string
    title: Private DB SubNet CIDR
    required: false
    visible: create_private_db
  
  private_db_subnet_name:
    type: string
    title: Private DB SubNet Name
    required: false
    visible: create_private_db

  create_private_exacs:
    type: boolean
    title: "Create ExaCS Client and Backup SubNets"
    description: "Check it if is necessary create ExaCS subnets"
    required: true

  private_exacs_client_subnet_cidr:
    type: string
    title: Private ExaCS client SubNet CIDR
    required: false
    visible: create_private_exacs

  private_exacs_client_subnet_name:
    type: string
    title: Private ExaCS Client SubNet Name
    required: false
    visible: create_private_exacs

  private_exacs_bkp_subnet_cidr:
    type: string
    title: Private ExaCS Backup SubNet CIDR
    required: false
    visible: create_private_exacs

  private_exacs_bkp_subnet_name:
    type: string
    title: Private ExaCS Backup SubNet Name
    required: false
    visible: create_private_exacs

  create_private_oke:
    type: boolean
    title: "Create OKE SubNet"
    description: "Check it if is necessary create dedicated OKE subnet"
    required: true

  private_oke_subnet_cidr:
    type: string
    title: Private OKE SubNet CIDR
    required: false
    visible: create_private_oke
  
  private_oke_subnet_name:
    type: string
    title: Private OKE SubNet Name
    required: false
    visible: create_private_oke

  create_private_gen1:
    type: boolean
    title: "Create Generic 1 SubNet"
    description: "Check it if is necessary create a generic subnet"
    required: true
    
  private_gen1_subnet_cidr:
    type: string
    title: Private Generic SubNet Name 1
    required: false
    visible: create_private_gen1

  private_gen1_subnet_name:
    type: string
    title: Private Generic SubNet Name 1
    required: false
    visible: create_private_gen1

  create_private_gen2:
    type: boolean
    title: "Create Generic 2 SubNet"
    description: "Check it if is necessary create a generic subnet"
    required: true

  private_gen2_subnet_cidr:
    type: string
    title: Private Generic SubNet CIDR 2
    required: false
    visible: create_private_gen2
  
  private_gen2_subnet_name:
    type: string
    title: Private Generic SubNet Name 2
    required: false
    visible: create_private_gen2
  
  vcn_dns_label:
    title: VCN DNS Label
    type: string
    required: false
    default: templatevcn

  lockdown_default_seclist:
    title: Enable VCN Default Security List Lockdown
    type: string
    required: false
    default: true

  attached_drg_id:
    title: DRG OCID to attach to the VCN
    type: string
    required: false
    default: null

  freeform_tags:
    type: map
    visible: false
